[package]
name = "x123"
description = "XChaCha12BLAKE3"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.4"
chacha20 = { version = "0.9", features = [ "zeroize" ] }
getrandom = "0.2"
zeroize = "1.6"